id: ICBCC2F9B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:39:24+00:00'
last_modified: '2022-06-10T11:12:20.943279+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18406
  title: གཡེར་གཤོང་མཁན་ཆེན་ཆོས་ཀྱི་རྒྱལ་པོའི་བཀའ་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    3DA3:
      image_group_id: I1KG18443
      title: Volume 1 of g.yer gshong mkhan chen chos kyi rgyal po'i bka' 'bum/
      total_pages: 782
      order: 1
      base_file: 3DA3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
